.eslintrc.json
.github/dependabot.yml
.github/workflows/codeql.yml
.github/workflows/nodejsci.yml
package-lock.json
package.json
src/domain/comment/Comment.ts
src/domain/creator/Creator.ts
src/domain/post/Post.ts
src/domain/rating/Rating.ts
src/domain/reaction/Reaction.ts
src/domain/relation/Relation.ts
src/frontend/App.tsx
src/frontend/main.tsx
src/jitar.ts
test/dummy.spec.ts
tsconfig.eslint.json
tsconfig.json
vite.config.js

What I've done:
* Set up testing
* Set up linting
* Set up GitHub Actions
* Dependabot
* CodeQL workflow
* Node.js CI workflow (build, test, lint)

chore(qa): Set up testing and linting

---

.github/workflows/nodejsci.yml
package-lock.json
package.json

Closes #16 
Closes #17 
Closes #18 
Closes #19 
Closes #20 
Closes #21 
@MaskingTechnology/dev

chore(deps): november updates

---

docker-compose.yml
package-lock.json
package.json
src/integrations/filestorage/definitions/errors.ts
src/integrations/filestorage/definitions/interfaces.ts
src/integrations/filestorage/implementation.ts
src/integrations/filestorage/implementations/MemoryFS.ts
src/integrations/filestorage/implementations/MinioFS.ts
src/integrations/filestorage/module.ts
test/integrations/filestorage/MemoryFS.spec.ts
test/integrations/filestorage/_fixtures/MemoryFS.fixture.ts

Fixes #29 
- Generic file storage interface
- In-memory implementation
- Minio implementation

29 add file storage support

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

Fixes #47
- template for pull request
- template for bugs
- template for features

chore: added templates for issues and pull requests

---

.gitignore
changelog.hbs
package-lock.json
package.json

Closes #24 
Changes proposed in this pull request
- added auto changelog for generating the changelog
- added npm pre publish script
- ignore any package that is created with npm pack
@petermasking

chore(build): added npm release configs

---

services/standalone.json
src/integrations/filestorage/definitions/interfaces.ts
src/integrations/filestorage/implementations/MemoryFS.ts
src/integrations/filestorage/implementations/MinioFS.ts
src/integrations/jitar/fileStorageHealthCheck.ts
src/integrations/jitar/healthchecks/FileStorageHealthCheck.ts
src/integrations/jitar/setUpNode.ts
src/integrations/jitar/tearDownNode.ts

#44: Added file storage health check

---

package-lock.json
package.json

Closes #52
Closes #53
Closes #54 
Closes #55 
Closes #56 
Closes #57 
- updated dependencies

chore(deps): january updates

---

.github/dependabot.yml

Fixes #59 
- Limited the number of open pull requests for dependabot to 1

chore(build): limit open pull requests for dependabot

---

package-lock.json
package.json
src/webui/designsystem/elements/button/Button.tsx

Fixes #64 
- bumped Jitar to 0.5.1
- bumped Vite to 5
- fixed issue found by Vite 5

chore(deps): bump jitar to 0.5.1

---

index.html
src/webui/designsystem/elements/image/Image.tsx
src/webui/designsystem/elements/panel/Panel.tsx
src/webui/designsystem/elements/ruler/Ruler.css
src/webui/layouts/authenticated/Authenticated.css
src/webui/layouts/authenticated/Authenticated.tsx
src/webui/layouts/entrance/Entrance.css
src/webui/layouts/entrance/Entrance.tsx
src/webui/layouts/home/Home.css
src/webui/layouts/home/Home.tsx

Fixes #60
- Home layout
- Entrance layout
- Authenticated layout
- fixed minor issues in elements

feat(webui): added layouts

---

docker-compose.yml

Fixes #72
- Updated mongo express config in the docker compose file
- Made it work

chore(integration): updated mongo express

---

src/domain/comic/Comic.ts
src/domain/comic/ComicData.ts
src/domain/comment/Comment.ts
src/domain/comment/CommentData.ts
src/domain/creator/Creator.ts
src/domain/creator/CreatorData.ts
src/domain/image/Image.ts
src/domain/image/ImageData.ts
src/domain/notification/Notification.ts
src/domain/notification/NotificationData.ts
src/domain/post/Post.ts
src/domain/post/PostData.ts
src/domain/rating/Rating.ts
src/domain/rating/RatingData.ts
src/domain/reaction/Reaction.ts
src/domain/reaction/ReactionData.ts
src/domain/relation/Relation.ts
src/domain/relation/RelationData.ts

Fixes #82 
- Set up data models
- Set up domain models

#82: Set up basic data and domain models

---

package-lock.json

#84: updated vite to latest

---

development.env
package-lock.json
package.json
segments/comic.segment.json
segments/comment.segment.json
segments/creator.segment.json
segments/image.segment.json
segments/notification.segment.json
segments/post.segment.json
segments/rating.segment.json
segments/reaction.segment.json
segments/relation.segment.json
services/standalone.json

Fixes #98 
- Updated Jitar dependency
- Protected access for data procedures
- Added trust key

#98: Updated Jitar to version 0.7

---

.eslintrc.json
.vscode/settings.json

Fixes #104
- updated config for auto sort
- updated eslint config to allow React to be not in scope for tsx files

chore: auto sort imports

---

src/webui/components/common/Loading.tsx
src/webui/components/module.ts
src/webui/designsystem/elements/spinner/Spinner.css
src/webui/designsystem/elements/spinner/Spinner.tsx
src/webui/designsystem/module.ts
src/webui/features/CreatorComics.tsx
src/webui/features/CreatorFollowers.tsx
src/webui/features/CreatorFollowing.tsx
src/webui/features/ExploreComics.tsx
src/webui/features/ExploreCreators.tsx
src/webui/features/Notifications.tsx
src/webui/features/Profile.tsx
src/webui/features/Timeline.tsx

Fixes #106 
- Spinner element in design system
- Loading common component
- Loading indication in features

feat(web-ui): loading component

---

src/webui/components/common/NoResults.tsx
src/webui/components/notification/PanelList.tsx
src/webui/components/post/PanelGrid.tsx
src/webui/components/post/PanelList.tsx
src/webui/components/relation/PanelList.tsx
src/webui/designsystem/elements/panel/Panel.css
src/webui/designsystem/elements/panel/Panel.tsx

Fixes #117 
- Added the no results component
- Added option to the Panel for transparent background (design system)
- Show the NoResults panel when needed

feat(webui): add no results component

---

src/webui/features/CreatorComics.tsx
src/webui/features/CreatorFollowers.tsx
src/webui/features/CreatorFollowing.tsx
src/webui/features/ExploreComics.tsx
src/webui/features/ExploreCreators.tsx
src/webui/features/Identify.tsx
src/webui/features/Login.tsx
src/webui/features/Notifications.tsx
src/webui/features/Profile.tsx
src/webui/features/Timeline.tsx
src/webui/utils/awaitData.ts
src/webui/utils/loadData.ts

Fixes #128 
- Utility function for loading data with cancel option
- Using this function in features that load data on initialization

#128: implemented util for loading data with cancel option

---

.vscode/settings.json

Fixes #141 
- removed javascript settings (unused)
- updated import behavior for typescript imports

feat(build): updated vscode settings

---

package-lock.json
package.json

Fixes #144 
- updated Jitar to latest version
- updated jose to fix security vulnerability

chore(deps): update jitar to version 0.7.3

---

LICENCE.md

Fixes #31
- added the AGPLv3 license

chore: added license

---

segments/webui.segment.json
src/domain/creator/decreaseFollowerCount.ts
src/domain/creator/decreaseFollowingCount.ts
src/domain/creator/increaseFollowerCount.ts
src/domain/creator/increaseFollowingCount.ts
src/domain/relation/establish.ts
src/domain/relation/view/RelationView.ts
src/webui/components/relation/Counters.tsx
src/webui/components/relation/Panel.tsx
src/webui/components/relation/PanelList.tsx
src/webui/components/relation/Profile.tsx
src/webui/components/relation/TimeElapsed.tsx
src/webui/components/relation/elementary/FollowButton.tsx
src/webui/components/relation/elementary/FollowRow.tsx
src/webui/features/ExploreCreators.tsx
src/webui/features/Profile.tsx
test/domain/relation/_fixtures/relation.fixture.ts
test/domain/relation/establish.spec.ts

Fixes #152 
- configured Follow button with state
- implement the HandleFollow function
- added follower/following counter updating
- introduced SAGA

feat(webui): follow explored creators

---

package-lock.json
package.json

chore(deps): added node types

---

package.json

Fixes #176 
- added `npm run review` to run everything needed before creating a pull request
- added `npm run rebuild` to build and start the standalone configuration

chore: added scripts for common actions

---

src/domain/post/data/retrieveWithoutCreators.ts
src/domain/post/explore.ts
src/webui/features/ExploreComics.tsx

Fixes #155
- implemented searching for posts from people the creator is not following

feat(domain): explore comics

---

src/webui/features/ExploreComics.tsx

Fixes #190 
- Follow handler implemented

feat(web-ui): follow from explored post

---

package.json
src/webui/components/notification/Panel.tsx
src/webui/components/notification/PanelList.tsx
src/webui/components/post/DetailsPanel.tsx
src/webui/components/reaction/LargePanel.tsx
src/webui/components/reaction/PanelList.tsx
src/webui/features/Notifications.tsx
src/webui/features/Post.tsx
src/webui/features/Reactions.tsx

Fixes #193
- Updated tsconfig location for build
- Added profileHandlers to components that needed them, but with dummy implementation

fix(build): changed tsconfig

---

src/webui/components/comment/Form.tsx
src/webui/components/module.ts
src/webui/designsystem/elements/modal/Modal.css
src/webui/designsystem/elements/modal/Modal.tsx
src/webui/designsystem/module.ts
src/webui/features/CreateReaction.tsx
src/webui/features/Profile.tsx
src/webui/features/Reactions.tsx

Fixes #192
- basic modal (no styling options)
- first use in the reactions feature (needs to be extended)

192 add modal support

---

services/standalone.json
src/domain/comic/data/create.ts
src/domain/comment/data/create.ts
src/domain/creator/data/create.ts
src/domain/creator/data/mapRecord.ts
src/domain/image/data/create.ts
src/domain/image/data/mapRecord.ts
src/domain/post/data/create.ts
src/domain/rating/data/create.ts
src/domain/reaction/data/create.ts
src/domain/relation/data/create.ts
src/domain/relation/data/mapRecord.ts
src/integrations/database/implementations/mongodb/MongoDb.ts
src/integrations/runtime/module.ts
src/integrations/validation/implementations/zod/Zod.ts
vite.config.ts

Fixes #225 
- completed rename of `jitar` to `runtime`
- generate ids in domain to be database independent
- refactored the joinedAt date to string in data record

chore(domain): generate id when creating object model

---

src/integrations/authentication/implementations/openid/OpenID.ts
src/integrations/database/implementations/mongodb/MongoDb.ts
src/integrations/filestore/implementations/minio/MinioFS.ts
src/integrations/notification/implementations/webpush/WebPush.ts
src/integrations/runtime/authenticationMiddleware.ts
src/integrations/runtime/databaseHealthCheck.ts
src/integrations/runtime/fileStoreHealthCheck.ts
src/integrations/runtime/healthchecks/DatabaseHealthCheck.ts
src/integrations/runtime/healthchecks/FileStoreHealthCheck.ts
src/integrations/runtime/healthchecks/NotificationHealthCheck.ts
src/integrations/runtime/middlewares/AuthenticationMiddleware.ts
src/integrations/runtime/middlewares/RequesterMiddleware.ts
src/integrations/runtime/notificationHealthCheck.ts
src/integrations/runtime/requesterMiddleware.ts
src/integrations/runtime/setUpGateway.ts
src/integrations/runtime/setUpNode.ts
src/integrations/runtime/tearDownGateway.ts
src/integrations/runtime/tearDownNode.ts
src/integrations/validation/implementations/zod/Zod.ts

Fixes #231
- refactored the imports that skip their own module to use `^/xyz/`

chore(integrations): refactored imports

---

example.env
src/domain/comic/create/feature.ts
src/domain/post/create/feature.ts
src/domain/post/remove/feature.ts
src/domain/post/toggleRating/feature.ts
src/domain/reaction/create/feature.ts
src/domain/reaction/createComic/feature.ts
src/domain/reaction/createComment/feature.ts
src/domain/reaction/remove/feature.ts
src/domain/reaction/toggleRating/feature.ts
src/domain/relation/establish/feature.ts
src/integrations/logging/Logger.ts
src/integrations/logging/definitions/interfaces.ts
src/integrations/logging/errors/LogError.ts
src/integrations/logging/errors/UnknownImplementation.ts
src/integrations/logging/implementation.ts
src/integrations/logging/implementations/console/Console.ts
src/integrations/logging/implementations/console/create.ts
src/integrations/logging/implementations/void/Void.ts
src/integrations/logging/implementations/void/create.ts
src/integrations/logging/module.ts

Fixes #234 
- Logging utility with processor interface
- Implementations for the default console and a void (no logging)
- fist logging use at failures of saga features

feat(integrations): logging

---

src/domain/comic/create/feature.ts
src/domain/post/create/feature.ts
src/domain/reaction/createComic/feature.ts
src/domain/reaction/createComment/feature.ts
test/domain/creator/updateNickname.spec.ts
test/domain/post/create.spec.ts
test/domain/reaction/create.spec.ts

Fixes #245 
- removed unnecessary sagas
- cleaned up the tests for checking only the absolute minimum when failing a saga

feat(domain): prepare for garbage collection

---

src/integrations/database/Database.ts
src/integrations/database/definitions/interfaces.ts
src/integrations/database/implementation.ts
src/integrations/database/implementations/memory/Memory.ts
src/integrations/database/implementations/mongodb/MongoDb.ts
src/integrations/database/module.ts
src/integrations/runtime/healthchecks/DatabaseHealthCheck.ts

Fixes #248 
- added Database object to have an additional layer between the driver and the application

feat(integration): database driver

---

package-lock.json

chore(dependencies): updated dependencies

---

src/webui/components/application/Sidebar.tsx
src/webui/designsystem/elements/column/Column.css
src/webui/designsystem/elements/row/Row.css
src/webui/editor/utils/CameraDialog.ts
src/webui/editor/utils/InputDialog.ts
src/webui/layouts/sidebar/Sidebar.css

Fixes #255 
- gap between left and right content
- column and row elements take 100% of space (width / height)
- alignment in sidebar

#255: fixed spacing issue

---

src/domain/relation/getFollowers/feature.ts
src/domain/relation/getFollowing/feature.ts
src/domain/relation/translateToRequester/feature.ts
src/domain/relation/translateToRequester/translate.ts
src/domain/relation/translateToRequester/types.ts
src/webui/hooks/useLoadData.ts
src/webui/hooks/usePagination.ts

Fixes #272 
- fixed relation mapping
- fixed paging reset

fix(domain): relation mapping

---

package-lock.json

chore(dependencies): update dependency ws

---

package-lock.json
package.json
src/domain/post/types.ts

chore(dependencies): vite plugin as dev dependency

---

src/domain/creator/cleanNickname/feature.ts
src/webui/components/creator/NicknameForm.tsx
test/domain/authentication/fixtures/values.fixture.ts

Fixes #278 
- convert all nicknames to lowercase

chore(domain): lowercase nicknames

---

src/webui/components/common/CompactNumber.tsx
src/webui/components/common/TimeElapsed.tsx
src/webui/components/notification/Panel.tsx
src/webui/designsystem/components/dropdown/Dropdown.tsx
src/webui/designsystem/components/tabs/Tabs.tsx
src/webui/designsystem/elements/avatar/Avatar.tsx
src/webui/designsystem/elements/border/Border.tsx
src/webui/designsystem/elements/button/Button.tsx
src/webui/designsystem/elements/cell/Cell.tsx
src/webui/designsystem/elements/clickarea/ClickArea.tsx
src/webui/designsystem/elements/column/Column.tsx
src/webui/designsystem/elements/form/Form.tsx
src/webui/designsystem/elements/grid/Grid.tsx
src/webui/designsystem/elements/image/Image.tsx
src/webui/designsystem/elements/link/Link.tsx
src/webui/designsystem/elements/modal/Modal.tsx
src/webui/designsystem/elements/panel/Panel.tsx
src/webui/designsystem/elements/paragraph/Paragraph.tsx
src/webui/designsystem/elements/row/Row.tsx
src/webui/designsystem/elements/ruler/Ruler.tsx
src/webui/designsystem/elements/select/Select.tsx
src/webui/designsystem/elements/text/Text.tsx
src/webui/designsystem/elements/textarea/TextArea.tsx
src/webui/designsystem/elements/textbox/TextBox.tsx
src/webui/designsystem/elements/title/Title.tsx

Fixes #281 
- default values set while destructering

chore(web-ui): refactored default values setup

---

src/webui/Routes.tsx
src/webui/components/application/MenuItem.tsx
src/webui/designsystem/components/tabs/Tab.tsx
src/webui/designsystem/components/tabs/Tabs.tsx
src/webui/features/CreateReaction.tsx
src/webui/features/Explore.tsx
src/webui/features/Profile.tsx
src/webui/hooks/index.ts
src/webui/hooks/usePathParam.ts

Fixes #284 
- enhanced tabs component
- usePathParam hook

feat(web-ui): tab routing

---

src/webui/components/common/PullToRefresh.tsx
src/webui/components/common/hooks/useRefreshOnPull.ts
src/webui/designsystem/elements/spinner/Spinner.css

Fixes #289 
- resizable spinner based on em calculation

feat(web-ui): resizable spinner

---

.github/workflows/nodejsci.yml
package.json
src/webui/components/application/Menu.tsx
src/webui/components/comic/hooks/useCreateHandler.ts
src/webui/components/comment/hooks/useCreateHandler.ts
src/webui/components/common/PullToRefresh.tsx
src/webui/components/common/hooks/useLoadOnScroll.ts
src/webui/components/common/hooks/useRefreshOnPull.ts
src/webui/components/creator/hooks/useFullNameFormHandler.ts
src/webui/components/creator/hooks/useNicknameFormHandler.ts
src/webui/components/post/DetailsPanel.tsx
src/webui/components/post/LargePanel.tsx
src/webui/components/rating/elementary/Icon.tsx
src/webui/components/rating/hooks/useEngagement.ts
src/webui/components/reaction/LargePanel.tsx
src/webui/components/reaction/elementary/Icon.tsx
src/webui/components/relation/Panel.tsx
src/webui/components/relation/hooks/useEstablish.ts
src/webui/designsystem/elements/column/Column.css
src/webui/designsystem/elements/row/Row.css
src/webui/editor/utils/Camera.ts
src/webui/editor/utils/CameraDialog.ts
src/webui/editor/utils/Geometry.ts
src/webui/editor/utils/InputManager.ts
src/webui/layouts/sidebar/Sidebar.css
src/webui/main.css
tsconfig.compile.json

Fixes #257
- enhanced pull-to-refresh and scrolling
- enhanced layout and component styling
- touch support in the editor
- camera availability check

feat(web-ui): mobile device support

---

src/domain/notification/create/feature.ts
src/domain/notification/definitions.ts
src/domain/post/toggleRating/feature.ts
src/domain/reaction/create/feature.ts
src/domain/reaction/toggleRating/feature.ts
src/domain/relation/establish/feature.ts
src/webui/components/notification/Panel.tsx
src/webui/components/notification/PanelList.tsx
src/webui/components/notification/elementary/AddedReaction.tsx
src/webui/features/Notifications.tsx
test/domain/notification/create.spec.ts

Fixes #307 
- create notification when a reaction added
- make comic in the notification clickable
- add test for reaction added notification

feat(domain): reaction added notification

---

.github/workflows/codeql.yml
src/domain/notification/create/feature.ts
src/domain/rating/exists/feature.ts
src/domain/rating/update/getData.ts
src/domain/reaction/remove/retrieveOwnedData.ts

Fixes #314
- typescript as language

chore(build): typescript as code scanning language

---

package-lock.json
package.json

chore(deps): updates

---

segments/bff.segment.json

bug: remove private functions

---

.github/workflows/codeql.yml

chore(build): codeql restored

---

package-lock.json
package.json

351 update dependencies

---

package-lock.json
package.json

Fixes #377 
- updated dependencies
- updated vitest to v3

chore(deps): february updates

---

vite.config.ts

Fixes #384 
- excluded PRC calls from service worker
- separated plugin config from its registration

fix: RPC calls from webui

---

eslint.config.js
package-lock.json
package.json
src/integrations/logging/implementations/console/Console.ts
src/webui/features/hooks/useReorderList.ts

Fixes #388 
- console cannot be used anymore, to prevent us from pushing code with debug statements.

#388: no console linting rule

---

docker-compose.yml

chore: fixed docker image versions

---

package-lock.json

Fixes #391
- enable the latest features of jitar

chore: updated jitar

---

package.json
services/reads.json
services/reads2.json

Fixes #396 
- load balancing makes more sense for the reads

chore: update demo scenario
